//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionAnswer
    {
        public int IDQA { get; set; }
        public string QACode { get; set; }
        public Nullable<int> IDSubject { get; set; }
        public byte[] QASound { get; set; }
        public byte[] QAPicture { get; set; }
        public string QAEngWord { get; set; }
        public string QAVietWord { get; set; }
        public string QAExample_Viet { get; set; }
        public string QAExample_Eng { get; set; }
        public string QAPronunciation { get; set; }
        public string TypeOfWord { get; set; }
    }
}
